[font]
size = 12.0

[font.bold]
family = "Fira Code"

[font.bold_italic]
family = "Fira Code"

[font.italic]
family = "Fira Code"

[font.normal]
family = "Fira Code"

[[hints.enabled]]
command = "open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
chars = "\f"
key = "K"
mode = "~Vi|~Search"
mods = "Command"

[[keyboard.bindings]]
action = "ClearHistory"
key = "K"
mode = "~Vi|~Search"
mods = "Command"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "ClearSelection"
key = "C"
mode = "Vi|~Search"
mods = "Command"

[[keyboard.bindings]]
action = "Hide"
key = "H"
mods = "Command"

[[keyboard.bindings]]
action = "HideOtherApplications"
key = "H"
mods = "Command|Alt"

[[keyboard.bindings]]
action = "Minimize"
key = "M"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Command|Control"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mode = "~Search"
mods = "Command"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mode = "~Search"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[27;5;49~"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[27;5;50~"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[27;5;51~"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[27;5;52~"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[27;5;53~"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[27;5;54~"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[27;5;55~"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[27;5;56~"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[27;5;57~"
key = "Key9"
mods = "Command"

[scrolling]
history = 100000
multiplier = 10

[window]
decorations = "full"
dynamic_padding = false
opacity = 0.95

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 2
y = 2
