import = ["~/.config/alacritty/themes/one_dark.toml"]
live_config_reload = true

[font]
size = 12.0

[font.normal]
family = "Fira Code"
style = "medium"

[font.bold]
family = "Fira Code"

[font.bold_italic]
family = "Fira Code"

[font.italic]
family = "Fira Code"

[scrolling]
history = 100000
multiplier = 10

[window]
decorations = "full"
dynamic_padding = false
opacity = 0.95

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 2
y = 2
